export const countries = [
  "🇦🇺 Australia",
  "🇦🇹 Austria",
  "🇧🇪 Belgium",
  "🇧🇷 Brazil",
  "🇨🇦 Canada",
  "🇨🇭 Switzerland",
  "🇨🇿 Czech Republic",
  "🇩🇪 Germany",
  "🇪🇸 Spain",
  "🇫🇮 Finland",
  "🇫🇷 France",
  "🇬🇧 UK",
  "🇭🇺 Hungary",
  "🇮🇪 Ireland",
  "🇮🇹 Italy",
  "🇯🇵 Japan",
  "🇱🇹 Lithuania",
  "🇳🇱 Netherlands",
  "🇳🇴 Norway",
  "🇵🇱 Poland",
  "🇵🇹 Portugal",
  "🇷🇺 Russia",
  "🇸🇪 Sweden",
  "🇹🇷 Turkey",
  "🇺🇸 USA",
  "🇺🇦 Ukraine",
  "🇺🇿 Uzbekistan",
  "🇻🇳 Vietnam",
  "🇿🇦 South Africa",
];
export const industries = [
  "🚀 Tech",
  "🏦 Finance",
  "🏥 Healthcare",
  "🏭 Manufacturing",
  "🏢 Business",
  "🏫 Education",
  "🏡 Real Estate",
  "🏛️ Government",
  "🏆 Sports",
  "🎨 Arts",
  "🎮 Gaming",
  "🎥 Media",
  "🎨 Design",
  "🥻 Fashion",
  "🌹 Beauty",
  "🍜 Food",
  "✈️ Travel",
  "🪩 Lifestyle",
  "🎭 Entertainment",
  "🎷 Music",
  "📅 Events",
  "🎼 Culture",
  "🙏 Religion",
  "🏢 Politics",
  "🔬 Science",
  "🌏 Environment",
  "⚡ Energy",
  "🚌 Transportation",
  "🏗️ Construction",
  "🌾 Agriculture",
  "⛏️ Mining",
];
